// Sets eggplant to support most date/time formats
set the timeInputFormat to Natural

get LoadData.readFile("C:\Users\Lenny JM\Projects\GitHub\EPF-Homework\Wunderlist Test Data\Test Data.csv")
put it into data

repeat with each item propList in data
	// Check if the list exists, if not create it
	if List.find(propList.list) is false
		List.create propList.list
	else
		Click (TEXT: propList.list)
	end if
	
	// Check if the todo exists, if not create it
	if Todo.find(propList.todo) is false
		Todo.create propList.todo
	end if	
	
	Todo.openDetailView propList.todo
	
	// If there's a subtask, add it to the todo	
	if propList.subtask is not empty		
		Todo.addSubtask propList.todo, propList.subtask		
	End if
	
	// If there's a date, add it to the todo
	if propList.date is not empty
		Todo.addDueDate propList.todo, propList.date
	end if
	
	Todo.closeDetailView
end repeat
